### ISSUE TITLE
NPE at xml layout

### ISSUE THREAD

**Issue by mpkr** [diegocarloslima/FloatingGroupExpandableListView#15]
Hi Diego, I got NPE whenever I open xml file that contains 
 <com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView
                android:id="@android:id/list"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scrollbars="none" />

Take a look at the picture
![capture](https://cloud.githubusercontent.com/assets/6811937/2816561/db0b2baa-cecb-11e3-89d0-1d1d74afb2ed.PNG)

and here is the full log:

java.lang.NullPointerException
Exception details are logged in Window > Show View > Error Log

java.lang.NullPointerException
    at android.widget.ExpandableListView.getFlatListPosition(ExpandableListView.java:911)
    at com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView.drawDefaultSelector(FloatingGroupExpandableListView.java:458)
    at com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView.dispatchDraw(FloatingGroupExpandableListView.java:203)
    at android.view.View.draw(View.java:14468)
    at android.widget.AbsListView.draw(AbsListView.java:3817)
    at android.view.View.draw(View.java:14350)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.draw(View.java:14348)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.draw(View.java:14348)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.draw(View.java:14468)
    at android.view.View.draw(View.java:14350)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.draw(View.java:14348)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.draw(View.java:14468)
    at android.view.View.draw(View.java:14350)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
    at android.view.View.draw(View.java:14468)

It's not cause any error in the app but it prevent editing the xml file in graphical.

**Comment by diegocarloslima** [comment]
Hey mpkr! Thanks for reporting again ;) I'll take a look on that and will fix asap.

**Comment by diegocarloslima** [comment]
Done! :+1:

**Comment by mpkr** [comment]
thanks, work like a charm
