### ISSUE TITLE
IllegalStateException because FloatingGroupExpandableListView was never registered

### ISSUE THREAD

**Issue by shekibobo** [diegocarloslima/FloatingGroupExpandableListView#20]
This library is fantastic, but there is one issue that is keeping me from using it. For some reason, if I navigate away from a fragment that uses a `FloatingGroupExpandableListView`, I get an `IllegalStateException` because the library tries to call `unregisterDataSetObserver`, despite my not using an observer, and never having registered the view. Stack trace is below:

``` java
06-09 19:23:47.308    1919-1919/com.example.android.myapp.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.android.myapp.app, PID: 1919
    java.lang.IllegalStateException: Observer com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView$6@52a1d58c was not registered.
            at android.database.Observable.unregisterObserver(Observable.java:69)
            at android.widget.BaseExpandableListAdapter.unregisterDataSetObserver(BaseExpandableListAdapter.java:42)
            at com.diegocarloslima.fgelv.lib.WrapperExpandableListAdapter.unregisterDataSetObserver(WrapperExpandableListAdapter.java:29)
            at com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView.onDetachedFromWindow(FloatingGroupExpandableListView.java:195)
            at android.view.View.dispatchDetachedFromWindow(View.java:12620)
            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
            at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2585)
            at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3845)
            at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3818)
            at android.view.ViewGroup.removeView(ViewGroup.java:3750)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:983)
            at android.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1167)
            at android.app.BackStackRecord.run(BackStackRecord.java:641)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
            at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by diegocarloslima** [comment]
Hi Joshua, thanks for reporting. For instance, I need more information to really know what is happening. If possible, I would ask you a snippet of code showing how you are using your fragment. Once I can reproduce this issue, It will be much easier to fix. It can be possibly related to the FragmentManager or to the observer attachment.

Currently, I have 1 suggestion I would like you to try. Inside the `FloatingGroupExpandableListView` class remove this:

```
@Override
protected void onAttachedToWindow() {
    super.onAttachedToWindow();

    if(mAdapter != null && mDataSetObserver == null) {
        mDataSetObserver = new DataSetObserver() {
            @Override
            public void onChanged() {
                mFloatingGroupView = null;
            }

            @Override
            public void onInvalidated() {
                mFloatingGroupView = null;
            }
        };
        mAdapter.registerDataSetObserver(mDataSetObserver);
    }
}
```

And modify the `setAdapter()` method do be like this:

```
public void setAdapter(WrapperExpandableListAdapter adapter) {
    super.setAdapter(adapter);
    if(mAdapter != null && mDataSetObserver != null) {
        mAdapter.unregisterDataSetObserver(mDataSetObserver);
        mDataSetObserver = null;
    }
    mAdapter = adapter;
    if(mAdapter != null && mDataSetObserver == null) {
        mDataSetObserver = new DataSetObserver() {
            @Override
            public void onChanged() {
                mFloatingGroupView = null;
            }

            @Override
            public void onInvalidated() {
                mFloatingGroupView = null;
            }
        };
        mAdapter.registerDataSetObserver(mDataSetObserver);
    }
}
```

Let me know if that solved the issue.

**Comment by bob9** [comment]
I have the same issue I have implemented your recommended fix and will advise if it works after some testing..

Nice library by the way... I was looking for something that did this years ago.

**Comment by diegocarloslima** [comment]
Hey @shekibobo, @bob9. Did any of you guys tested the solution? Please let me know if that fixed this problem so I can update the lib with the fix

**Comment by bob9** [comment]
That fix seems to work for illegal state issue..  However I have found the
performance of the library when the child cell is a little more complicated
is not very smooth. When I disable the floating header library the
scrolling is smooth again.

**Comment by vivekwarde** [comment]
@diegocarloslima I am also facing the problem what @bob9 said about about the scrolling smoothness when many groups with many childs, How can we fix this problem ?
