### ISSUE TITLE
NullPointerException in view measure

### ISSUE THREAD

**Issue by prateek1306** [diegocarloslima/FloatingGroupExpandableListView#27]
Hi,
My app is crashing on scrolling the list in emulator and some Sony Ericsson devices. I found that the crash started coming after this commit https://github.com/diegocarloslima/FloatingGroupExpandableListView/commit/1e3f7b0c9400d110a8c6df047ceb2ffcc7ef80d1
According to the error logs, the crash is because of a NullPointerException in `RelativeLayout.onMeasure` - which is called by `mFloatingGroupView.measure(childWidthSpec, childHeightSpec);`

**Comment by prateek1306** [comment]
Looks like there is some bug in RelativeLayout as mentioned in `makeMeasure` section of `MeasureSpec` : http://developer.android.com/reference/android/view/View.MeasureSpec.html

> Note: On API level 17 and lower, makeMeasureSpec's implementation was such that the order of arguments did not matter and overflow in either value could impact the resulting MeasureSpec. RelativeLayout was affected by this bug. Apps targeting API levels greater than 17 will get the fixed, more strict behavior.

**Comment by diegocarloslima** [comment]
Hi, thanks for your contribution. Could you please post the full stacktrace of the npe? I'm not able to reproduce this issue

**Comment by prateek1306** [comment]
I could confirm that this happens on API-17 emulator. Have not tried yet on API-19 emulator.

Stack trace:

> FATAL EXCEPTION: main
> java.lang.NullPointerException
>     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:559)
>     at android.view.View.measure(View.java:15518)
>     at com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView.createFloatingGroupView(FloatingGroupExpandableListView.java:428)
>     at com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView.access$3(FloatingGroupExpandableListView.java:356)
>     at com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView$1.onScroll(FloatingGroupExpandableListView.java:108)
>     at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:1340)
>     at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4949)
>     at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4087)
>     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
>     at android.view.Choreographer.doCallbacks(Choreographer.java:562)
>     at android.view.Choreographer.doFrame(Choreographer.java:531)
>     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
>     at android.os.Handler.handleCallback(Handler.java:725)
>     at android.os.Handler.dispatchMessage(Handler.java:92)
>     at android.os.Looper.loop(Looper.java:137)
>     at android.app.ActivityThread.main(ActivityThread.java:5041)
>     at java.lang.reflect.Method.invokeNative(Native Method)
>     at java.lang.reflect.Method.invoke(Method.java:511)
>     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
>     at dalvik.system.NativeStart.main(Native Method)

**Comment by diegocarloslima** [comment]
Hey @prateek1306 I think I solved it. Could you please pull my last commit and check it?

**Comment by prateek1306** [comment]
@diegocarloslima Its fixed now. Thanks!

**Comment by thelou1s** [comment]
My npe logs are a little different:

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getImportantForAccessibility()' on a null object reference
    at android.widget.AbsListView.obtainView(AbsListView.java:2363)
    at android.widget.ListView.measureHeightOfChildren(ListView.java:1281)
    at android.widget.ListView.onMeasure(ListView.java:1188)
    at com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView.onMeasure(FloatingGroupExpandableListView.java:204)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1112)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:632)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
    at android.view.View.measure(View.java:18794)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:606)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
