### ISSUE TITLE
Sometimes IndexOutOfBoundsException?

### ISSUE THREAD

**Issue by imoblife** [diegocarloslima/FloatingGroupExpandableListView#29]
1st log:
java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
    at java.util.ArrayList.get(ArrayList.java:304)
    at base.util.ui.listview.ExpandListAdapter.getGroup(ExpandListAdapter.java)
    at my.package.Fragment$Adapter.getGroupView(Fragment.java)
    at com.diegocarloslima.fgelv.lib.WrapperExpandableListAdapter.getGroupView(WrapperExpandableListAdapter.java)
    at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:450)

2nd log:
java.lang.ArrayIndexOutOfBoundsException
at android.view.MotionEvent.getY(MotionEvent.java:934)
at android.widget.AbsListView.onTouchEvent(AbsListView.java:2263)
at android.widget.ListView.onTouchEvent(ListView.java:3492)
at com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView.onTouchEvent(FloatingGroupExpandableListView.java:312)
at android.view.View.dispatchTouchEvent(View.java:3934)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:934)
at com.diegocarloslima.fgelv.lib.FloatingGroupExpandableListView.dispatchTouchEvent(FloatingGroupExpandableListView.java:301)

**Comment by diegocarloslima** [comment]
Hi @imoblife, sorry for the delay... I've been very busy :/ Are you still experiencing this issue? From the 1st log my guess is that something related to your adapter, not a bug in the lib itself

**Comment by imoblife** [comment]
The 1st is ok, but how about the 2nd?

**Comment by diegocarloslima** [comment]
Hey @imoblife, with which version of android are you compiling your app? Is possible for you for sending me a sample code where I can reproduce this?

**Comment by thelou1s** [comment]
@diegocarloslima  Hi, imoblife and I are the same, I didn't notice your reply before. And the exception grows fast recently, so here is all related files. Please feel free to contact me, thank you :)

[AClean.java.txt](https://github.com/diegocarloslima/FloatingGroupExpandableListView/files/392775/AClean.java.txt)

[clean_activity.xml.txt](https://github.com/diegocarloslima/FloatingGroupExpandableListView/files/392777/clean_activity.xml.txt)

**Comment by thelou1s** [comment]
the crash was caused by collapseGroup() on onGroupClick(), while Accessibility Service should be enabled:

```
onGroupClick() {
...parent.collapseGroup(groupPosition);
}
```

```
08-05 11:20:28.066: E/AndroidRuntime(11508): java.lang.IndexOutOfBoundsException: Invalid index 13, size is 0
08-05 11:20:28.066: E/AndroidRuntime(11508):    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at java.util.ArrayList.get(ArrayList.java:308)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.widget.AbsListView.onInitializeAccessibilityNodeInfoForItem(AbsListView.java:2553)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.widget.ListView.onInitializeAccessibilityNodeInfoForItem(ListView.java:3946)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.widget.AbsListView$ListItemAccessibilityDelegate.onInitializeAccessibilityNodeInfo(AbsListView.java:2484)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6104)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.View.createAccessibilityNodeInfoInternal(View.java:6065)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:22414)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.View.createAccessibilityNodeInfo(View.java:6048)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.View.onInitializeAccessibilityEventInternal(View.java:6002)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:22326)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.View.onInitializeAccessibilityEvent(View.java:5988)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5855)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:22265)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.View.sendAccessibilityEventUnchecked(View.java:5838)
08-05 11:20:28.066: E/AndroidRuntime(11508):    at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.run(ViewRootImpl.java:7377)
```
